# Generated by Django 4.2.10 on 2024-02-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissoes.paginas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedores.vendedores')),
            ],
        ),
    ]
