# Generated by Django 4.2.10 on 2024-02-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
        ('clientes', '0002_alter_cliente_cpf'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('cheque', 'Cheque'), ('boleto', 'Boleto'), ('pix', 'Pix')], max_length=20)),
                ('observacoes', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedores.vendedores')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'vendas',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='ItensVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.vendas')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Vendas',
                'db_table': 'itens_vendas',
                'ordering': ['id'],
                'unique_together': {('venda', 'produto', 'is_active')},
            },
        ),
    ]
