# Generated by Django 4.2.10 on 2024-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
