# Generated by Django 4.2.10 on 2024-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_vendas_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
